better scripting

diff --git a/.github/actions/common/validate/action.yml b/.github/actions/common/validate/action.yml
--- a/.github/actions/common/validate/action.yml
+++ b/.github/actions/common/validate/action.yml
@@ -10,10 +10,6 @@ inputs:
     description: 'username used for automated commits which should not trigger actions'
     required: false
     default: "github-actions[bot]"
-  type: #TODO: remove in future
-    description: 'execution type (snapshot / release)'
-    required: false
-    default: "release"
 
 outputs:
   repository_type:
@@ -57,46 +53,7 @@ runs:
       id: checkout
       uses: actions/checkout@v4
 
-    - name: should image be published
-      id: should_publish
-      shell: bash
-      run: |
-        COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
-        if [[ "${COMMIT_AUTHOR}" == "${{ inputs.GITHUB_ACTIONS_USERNAME }}" ]]; then
-          echo "::warning::SKIP: action is triggered by automated commit"
-          echo "required=false" >> $GITHUB_OUTPUT
-        else
-          echo "triggered by ${COMMIT_AUTHOR}"
-          echo "required=true" >> $GITHUB_OUTPUT
-        fi
-
-    - name: should run workflow
-      id: should_run
-      shell: bash
-      run: |
-        SHOULD_PUBLISH=${{ steps.should_publish.outputs.required }}
-        if [[ "${SHOULD_PUBLISH}" == "false" ]] \
-             && [[ "${{ inputs.type }}" != "release" ]]; then
-          echo "::error::Workflow should not be executed"
-          echo "::warning::should_publish is ${SHOULD_PUBLISH}"
-        
-          echo "SKIP: workflow execution being skipped by:" >> $GITHUB_STEP_SUMMARY
-          echo "should_publish: ${SHOULD_PUBLISH}" >> $GITHUB_STEP_SUMMARY
-        
-          exit 1
-        fi
-
-    - name: check repository vars
-      id: repository
-      shell: bash
-      run: |
-        TYPE=$(jq -r '.repository.custom_properties.type     | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
-        LANG=$(jq -r '.repository.custom_properties.language | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
-        echo "type=$TYPE" >> $GITHUB_OUTPUT
-        echo "language=$LANG" >> $GITHUB_OUTPUT
-
-    - name: check environment name
-      id: environment
+    - id: environment
       shell: bash
       run: |
         EVENT_NAME=${{ github.event_name }}
@@ -111,3 +68,41 @@ runs:
           echo "Environmane name is: TEST"
           echo "name=TEST" >> $GITHUB_OUTPUT
         fi
+
+    - name: should image be published
+      id: author
+      shell: bash
+      run: |
+        COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
+        if [[ "${COMMIT_AUTHOR}" == "${{ inputs.GITHUB_ACTIONS_USERNAME }}" ]]; then
+          echo "::warning::SKIP: action is triggered by automated commit"
+          echo "is_bot=true" >> $GITHUB_OUTPUT
+        else
+          echo "triggered by ${COMMIT_AUTHOR}"
+          echo "is_bot=false" >> $GITHUB_OUTPUT
+        fi
+
+    - name: should run workflow
+      id: should_run
+      shell: bash
+      run: |
+        IS_BOT=${{ steps.author.outputs.is_bot }}
+        if [[ "${IS_BOT}" == "true" ]] \
+             && [[ "${{ github.event_name }}" != "release" ]]; then
+          echo "::error::Workflow should not be executed"
+          echo "::warning::latest commit is bot(${IS_BOT})"
+        
+          echo "SKIP: workflow execution being skipped by:" >> $GITHUB_STEP_SUMMARY
+          echo "latest commit is bot(${IS_BOT})" >> $GITHUB_STEP_SUMMARY
+        
+          exit 1
+        fi
+
+    - name: check repository vars
+      id: repository
+      shell: bash
+      run: |
+        TYPE=$(jq -r '.repository.custom_properties.type     | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
+        LANG=$(jq -r '.repository.custom_properties.language | select(. != null and . != "unknown") // "default"' < "$GITHUB_EVENT_PATH")
+        echo "type=$TYPE" >> $GITHUB_OUTPUT
+        echo "language=$LANG" >> $GITHUB_OUTPUT
